version: "3.8"
services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    hostname: app-mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      - main-network
    command: ["--bind_ip", "0.0.0.0"]
    
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: bookservice
    container_name: bookservice
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - 8080:8080
    networks:
      - main-network

networks:
  main-network:
    driver: bridge